- entries:
  - jsonPayload:
      message: |-
        2019/01/15 07:48:05 http: panic serving [::1]:54143: test panic
        goroutine 24 [running]:
        net/http.(*conn).serve.func1(0xc00007eaa0)
        	/usr/local/go/src/net/http/server.go:1746 +0xd0
        panic(0x12472a0, 0x12ece10)
        	/usr/local/go/src/runtime/panic.go:513 +0x1b9
        main.doPanic(0x12f0ea0, 0xc00010e1c0, 0xc000104400)
        	/Users/ingvar/src/go/src/httppanic.go:8 +0x39
        net/http.HandlerFunc.ServeHTTP(0x12be2e8, 0x12f0ea0, 0xc00010e1c0, 0xc000104400)
        	/usr/local/go/src/net/http/server.go:1964 +0x44
        net/http.(*ServeMux).ServeHTTP(0x14a17a0, 0x12f0ea0, 0xc00010e1c0, 0xc000104400)
        	/usr/local/go/src/net/http/server.go:2361 +0x127
        net/http.serverHandler.ServeHTTP(0xc000085040, 0x12f0ea0, 0xc00010e1c0, 0xc000104400)
        	/usr/local/go/src/net/http/server.go:2741 +0xab
        net/http.(*conn).serve(0xc00007eaa0, 0x12f10a0, 0xc00008a780)
        	/usr/local/go/src/net/http/server.go:1847 +0x646
        created by net/http.(*Server).Serve
        	/usr/local/go/src/net/http/server.go:2851 +0x2f5
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/transformation_test
    timestamp: now
  - jsonPayload:
      message: |-
        Traceback (most recent call last):
          File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
            rv = self.handle_exception(request, response, e)
          File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start
            return get()
          File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get
            raise Exception('spam', 'eggs')
        Exception: ('spam', 'eggs')
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/transformation_test
    timestamp: now
  - jsonPayload:
      message: |-
        2023-07-09 00:00:00,000 ERROR    some_app custom string prefix to the exception: Traceback (most recent call last):
          File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
            rv = self.handle_exception(request, response, e)
          File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start
            return get()
          File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get
            raise Exception('spam', 'eggs')
        Exception: ('spam', 'eggs')
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/transformation_test
    timestamp: now
  partialSuccess: true
  resource:
    labels: {}
    type: gce_instance
